glucosapp/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views
from readings.views import *
from registers.views import *
from anxiety_registers.views import *
from food_specs.views import *


urlpatterns = [
    #path('', ReadingListView.as_view(), name='home'),
    path('', views.index, name='home'),
    path('users/login', views.login_view, name='login'),
    path('users/logout', views.logout_view, name='logout'),
    path('users/register', views.register_view, name='register'),
    path('admin/', admin.site.urls),
    path('glucosapp/', views.landing, name='landing'),
    path('readings/', include('readings.urls')),
    path('registers/', include('registers.urls')),
    path('mental_health/', include('anxiety_registers.urls')),
    path('food_specs/', include('food_specs.urls')),
]

readings/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ReadingListView.as_view(), name='list_readings'),
    path('search/', views.ReadingSearchListView.as_view(), name='search'),
    path('<slug:slug>/', views.ReadingDetailView.as_view(), name='reading_detail'),
    path('<int:pk>/delete/', views.ReadingDeleteView.as_view(), name='reading_delete'),
]

anxiety_registers/models.py
import random
from django.db import models
from django.utils.text import slugify

from users.models import User

class Anxiety(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    anxiety_level = models.IntegerField()
    panic_attack = models.BooleanField()
    notes = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=False, blank=False, unique=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(f'{str(random.randint(1, 100))}{str(random.randint(1, 100))}{str(random.randint(1, 100))}{str(random.randint(1, 100))}{str(random.randint(1, 100))}{str(random.randint(1, 100))}')
        super(Anxiety, self).save(*args, **kwargs)


    def __str__(self):
        return f"{self.user} anxiety on {self.created_at}"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Glucosapp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
        
        {% include 'messages.html' %}
        
        <div class="row mt-3">
            {% block content %}

            {% endblock %}
        </div>
    </div>
    

<script src="https://kit.fontawesome.com/df593cd35b.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% include 'main.html' %}
{% endblock %}

<!--
    <ul class="list-group">
        {% for reading in object_list %}
            <li class="list-group-item">{{ reading.reading_value }} {{ reading.category.units }} {{ reading.category.name }}</li>
        {% endfor %}
    </ul>-->

<!--
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}">
                <button type="button" class="close" data-dismiss="alert"></button>
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col">
                <img src="{% static 'images/wolf.png' %}" alt="">
                <h1>{{ message }}</h1>

                <ul class="list-group">
                    {% for category in categories %}
                        <li class="list-group-item">{{ category.type }}
                            {% if category.is_active %}
                            <span class="text-success">Disponible</span>
                            {% else %}
                            <span class="text-danger">No Disponible</span>
                            {% endif %}
                        </li>
                        <li class="list-group-item">{{ category.description }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
-->
    <!--Bootstrap CDN Scripts, CSS Link in Head-->
<!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>
-->

templates/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Glucosapp</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body class="body-landing">
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 text-center">
            <h1>Bienvenido a Glucosapp</h1>
            <h4>Una aplicación para llevar los registros de tu diabetes</h4>
            <div class="mt-5">
                <a href="{% url 'login' %}" class="btn btn-landing btn-primary btn-lg mr-4">Iniciar Sesión</a>
                <a href="{% url 'register' %}" class="btn btn-landing btn-primary btn-lg mr-4">Registrarse</a>
                <a href="http://fermavec.com" class="btn btn-landing btn-primary btn-lg">Sitio Fer Mavec</a>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/main.html
{% load static %}

<div class="row pb-6">
    <div class="col-md-6 align-baseline">
      <h1 class="top-m text-left">Bienvenido {{ user.username.capitalize }}</h1>
    </div>
    </div>
    <h4>Selecciona la opción deseada:</h4>
    <hr>
    <div class="col-md-4 items-center">
        <a href="{% url 'level_register' %}" class="card text-center center links">
            <div class="card-body reg-card">
                <img class="main-icon" src="{% static 'img/add.svg' %}" alt="Agregar control">
                <h5 class="card-title">Agregar Registro</h5>
                <p class="card-text">Ingresa un nuevo registro de control para la diabetes</p>
            </div>
        </a>
    </div>
    <div class="col-md-4 items-center">
        <a href="{% url 'list_readings' %}" class="card text-center center links">
            <div class="card-body reg-card">
                <img class="main-icon" src="{% static 'img/table.svg' %}" alt="Listado de Control de Diabetes">
                <h5 class="card-title">Control de Diabetes</h5>
                <p class="card-text">Listado de todos tus registros de control</p>
            </div>
        </a>
    </div>
    <div class="col-md-4 items-center">
        <a href="{% url 'anxiety_register' %}" class="card text-center center links">
            <div class="card-body reg-card">
                <img class="main-icon" src="{% static 'img/brain.svg' %}" alt="Agregar eventos de ansiedad">
                <h5 class="card-title">Evento de Ansiedad</h5>
                <p class="card-text">Agrega un evento a tu bitácora de ansiedad</p>
            </div>
        </a>
    </div>
    
    <!--Segunda Fila-->
    <div class="col-md-4 items-center">
        <a href="{% url 'anxiety_list' %}" class="card text-center center links">
            <div class="card-body reg-card">
                <img class="main-icon" src="{% static 'img/book.svg' %}" alt="Bitacora de registros de ansiedad">
                <h5 class="card-title">Bitácora de Ansiedad</h5>
                <p class="card-text">Lista con todos los eventos de ansiedad registrados</p>
            </div>
        </a>
    </div>
    <!--Idea, poner un listado de las equivalencias de alimentos-->
    <div class="col-md-4 items-center">
        <a href="{% url 'list_food' %}" class="card text-center center links">
            <div class="card-body reg-card">
                <img class="main-icon" src="{% static 'img/burger.svg' %}" alt="">
                <h5 class="card-title">Equivalencias de Alimentos</h5>
                <p class="card-text">Listado del Sistema Mexicano de Alimentos Equivalentes</p>
            </div>
        </a>
    </div>
    <!--Idea, poner un Analytics-->
    <div class="col-md-4 items-center">
        <a href="#" class="card text-center center links">
            <div class="card-body reg-card">
                <img class="main-icon" src="{% static 'img/chart.svg' %}" alt="Analytics">
                <h5 class="card-title">Analítica</h5>
                <p class="card-text">Encuentra Insights sobre tus registros</p>
            </div>
        </a>
    </div>
    <tr>
</div>

templates/messages.html
{% if messages %}
            {% for message in messages %}
            <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}">
                <button type="button" class="close" data-dismiss="alert"></button>
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark main-bar  nav-mob">
    <div class="container">
    <a href="{% url 'home' %}" class="navbar-brand">FM Glucosapp</a>
    </div>

    <div class="container main-menu">
    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link">
                    <span class="fas fa-sign-in-alt"></span> Logout
                </a>
            </li>
        {% else %}
            <li class="nav-item {% if request.path == login %} active {% endif %}">
                <a href="{{ login }}" class="nav-link">
                    <span class="fas fa-user"></span> Login
                </a>
            </li>
            <li class="nav-item {% if request.path == register %}active{% endif %}">
                <a href="{{ register }}" class="nav-link">
                    <span class="fas fa-user-plus"></span> Registro
                </a>
            </li>
        {% endif %}

        <li class="nav-item">
            <a href="http://fermavec.com" class="nav-link">
                <span class="fas fa-link"></span> Fer Mavec
            </a>
        </li>
    </ul>
    </div>
</nav>